
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "YOUR_OWN_RANDOM_GENERATED_STRING"
MAPBOX_API_KEY = "pk.eyJ1IjoibnRkMjg0IiwiYSI6ImNsd2c5Z3BsZjAyYjAya25yZGhzNmRobGgifQ.rFDhRUYsjM7BLQVhOBkXjQ"